# -*- coding: utf-8 -*-
"""Esercizio_dizionario_parole.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/150MsFXp2qRz6dNCPtEhdMOa5irLhbdf0
"""

# dizionario che conta quante volte una parola appare in una stringa


txt = "a b c prova prova prova"

frase = txt.split()

diz={}

for parola in frase:
  if parola not in diz:
    diz[parola]=1
  else:
      diz[parola]+=1

print(diz)