# -*- coding: utf-8 -*-
"""Esercizio_dizionario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13M3icXgw1PWIIFdHcUdGRUe6zPmQOJUT
"""

# ESERCIZIO CORRETTO PER CONTARE LETTERE CON DIZIONARIO

stringa=input('inserisci una parola:')

diz={}

for lettera in stringa:
  if lettera not in diz:
    diz[lettera]=1
  else:
    diz[lettera]+=1

print(diz)

stringa=input('inserisci una stringa')

alfabeto='abcdefghijklmnopqrstuvwxyz'

counter=[0]*len(alfabeto)


for i in range(len(alfabeto)):
      for k in range(len(stringa)):
          if alfabeto[i]==stringa[k]:
            counter[i]+=1


print(counter)



dizionario={}


for i in range(len(alfabeto)):
      for k in range(len(stringa)):
          if alfabeto[i]==stringa[k]:
            dizionario[]

# Dato un elenco di parole, contare quante volte appare ciascuna parola utilizzando un ciclo for e un dizionario.
# parole = ["casa", "albero", "cane", "casa", "cane", "gatto", "cane"]


parole = ["casa", "albero", "cane", "casa", "cane", "gatto", "cane"]
dizionario = {}

for parola in parole:
  if parola not in dizionario:
    dizionario[parola]=1
  else:
    dizionario[parola]+=1

for chiave, valori in dizionario.items():
  print(chiave, valori)

# Dato un elenco di parole, contare quante volte appare ciascuna parola utilizzando un ciclo for e un dizionario.
# parole = ["casa", "albero", "cane", "casa", "cane", "gatto", "cane"]


parole = ["casa", "albero", "cane", "casa", "cane", "gatto", "cane"]
dizionario = {}

for parola in parole:
      print(parola)

